### ISSUE TITLE
Please specify the license your flymake-* packages are released under

### ISSUE THREAD

**Issue by tarsius** [purcell/flymake-coffee#11]
Hi Steve,

Could you please specify the licenses your `flymake-*` packages (and two others) are released under? I wasn't able to extract that information from: `flymake-coffee`, `flymake-css`, `flymake-haml`, `flymake-haskell-multi`, `flymake-hlint`, `flymake-jslint`, `flymake-json`, `flymake-php`, `flymake-python-pyflakes`, `flymake-ruby`, `flymake-sass`, `flymake-shell`, `hippie-expand-slime`, and `unfill`.

Thanks!

**Comment by purcell** [comment]
Let's go with GPLv3. I don't really want to go through and update all the repos, because most are (hopefully) pretty redundant now that Flycheck is here -- are you okay with me just noting the licence here?

**Comment by tarsius** [comment]
Others won't know that they have to come here to learn the licensing term, so you can't really get around touching all these repositories. But with the following tooling all you have to do is yank the permission statement in the correct place and then press `<f1>`, 15 times:

```lisp
(dolist (name '("flymake-coffee" "flymake-css" "flymake-haml" "flymake-haskell-multi" "flymake-hlint" "flymake-jslint" "flymake-json" "flymake-php" "flymake-python-pyflakes" "flymake-ruby" "flymake-sass" "flymake-shell" "hippie-expand-slime" "unfill"))
  (magit-git "clone"
             (format "git@github.com:purcell/%s.git" name)
             (concat "/tmp/" name))
  (find-file-other-frame (format "/tmp/%s/%s.el" name name)))

(global-set-key (kbd "<f1>")
  (lambda ()
    (interactive)
    (save-buffer)
    (magit-git "commit" "--all" "-m" "Add permission statement")
    (magit-git "push")
    (delete-frame)))
```

But there's no hurry. Sorry for putting more on your plate.

**Comment by purcell** [comment]
Thanks for the prod. I semi-automated it, and now it's done. :-)

**Comment by tarsius** [comment]
Thanks!
